--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-10-16 23:50:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 236 (class 1259 OID 118923)
-- Name: account_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_account (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    create_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_account OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 118922)
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 118929)
-- Name: account_budget; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_budget (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    user_id integer NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.account_budget OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 118928)
-- Name: account_budget_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_budget ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_budget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 118907)
-- Name: account_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.account_category OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 118906)
-- Name: account_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 118935)
-- Name: account_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_notification (
    id bigint NOT NULL,
    notify_type character varying(25) NOT NULL,
    message text NOT NULL,
    notification_date timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    is_delete boolean NOT NULL,
    category_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_notification OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 118934)
-- Name: account_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 118943)
-- Name: account_savingsgoal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_savingsgoal (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    target_amount numeric(10,2) NOT NULL,
    current_amount numeric(10,2) NOT NULL,
    target_date date NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_savingsgoal OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 118942)
-- Name: account_savingsgoal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_savingsgoal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_savingsgoal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 118915)
-- Name: account_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_tag (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.account_tag OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 118914)
-- Name: account_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 118949)
-- Name: account_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_transaction (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    create_at timestamp with time zone NOT NULL,
    description character varying(255) NOT NULL,
    transaction_type character varying(7) NOT NULL,
    account_id bigint NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.account_transaction OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 118948)
-- Name: account_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 118955)
-- Name: account_transaction_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_transaction_tags (
    id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.account_transaction_tags OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 118954)
-- Name: account_transaction_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_transaction_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_transaction_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 118821)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 118820)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 118829)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 118828)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 118835)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 118843)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 118842)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 118834)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 118849)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 118848)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 119054)
-- Name: authen_profilepicture; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authen_profilepicture (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authen_profilepicture OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 119053)
-- Name: authen_profilepicture_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authen_profilepicture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authen_profilepicture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4797 (class 2606 OID 118927)
-- Name: account_account account_account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_account
    ADD CONSTRAINT account_account_pkey PRIMARY KEY (id);


--
-- TOC entry 4801 (class 2606 OID 118933)
-- Name: account_budget account_budget_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_budget
    ADD CONSTRAINT account_budget_pkey PRIMARY KEY (id);


--
-- TOC entry 4788 (class 2606 OID 118913)
-- Name: account_category account_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_category
    ADD CONSTRAINT account_category_name_key UNIQUE (name);


--
-- TOC entry 4790 (class 2606 OID 118911)
-- Name: account_category account_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_category
    ADD CONSTRAINT account_category_pkey PRIMARY KEY (id);


--
-- TOC entry 4805 (class 2606 OID 118941)
-- Name: account_notification account_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_notification
    ADD CONSTRAINT account_notification_pkey PRIMARY KEY (id);


--
-- TOC entry 4808 (class 2606 OID 118947)
-- Name: account_savingsgoal account_savingsgoal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_savingsgoal
    ADD CONSTRAINT account_savingsgoal_pkey PRIMARY KEY (id);


--
-- TOC entry 4793 (class 2606 OID 118921)
-- Name: account_tag account_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_tag
    ADD CONSTRAINT account_tag_name_key UNIQUE (name);


--
-- TOC entry 4795 (class 2606 OID 118919)
-- Name: account_tag account_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_tag
    ADD CONSTRAINT account_tag_pkey PRIMARY KEY (id);


--
-- TOC entry 4813 (class 2606 OID 118953)
-- Name: account_transaction account_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_transaction
    ADD CONSTRAINT account_transaction_pkey PRIMARY KEY (id);


--
-- TOC entry 4815 (class 2606 OID 118959)
-- Name: account_transaction_tags account_transaction_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_transaction_tags
    ADD CONSTRAINT account_transaction_tags_pkey PRIMARY KEY (id);


--
-- TOC entry 4819 (class 2606 OID 119011)
-- Name: account_transaction_tags account_transaction_tags_transaction_id_tag_id_fcd3c3e1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_transaction_tags
    ADD CONSTRAINT account_transaction_tags_transaction_id_tag_id_fcd3c3e1_uniq UNIQUE (transaction_id, tag_id);


--
-- TOC entry 4760 (class 2606 OID 119051)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4765 (class 2606 OID 118864)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4768 (class 2606 OID 118833)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4762 (class 2606 OID 118825)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4776 (class 2606 OID 118847)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4779 (class 2606 OID 118879)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4770 (class 2606 OID 118839)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4782 (class 2606 OID 118853)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4785 (class 2606 OID 118893)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4773 (class 2606 OID 119046)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4821 (class 2606 OID 119058)
-- Name: authen_profilepicture authen_profilepicture_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authen_profilepicture
    ADD CONSTRAINT authen_profilepicture_pkey PRIMARY KEY (id);


--
-- TOC entry 4823 (class 2606 OID 119060)
-- Name: authen_profilepicture authen_profilepicture_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authen_profilepicture
    ADD CONSTRAINT authen_profilepicture_user_id_key UNIQUE (user_id);


--
-- TOC entry 4798 (class 1259 OID 118967)
-- Name: account_account_user_id_8d4f4816; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_account_user_id_8d4f4816 ON public.account_account USING btree (user_id);


--
-- TOC entry 4799 (class 1259 OID 118979)
-- Name: account_budget_category_id_f50af18e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_budget_category_id_f50af18e ON public.account_budget USING btree (category_id);


--
-- TOC entry 4802 (class 1259 OID 118978)
-- Name: account_budget_user_id_5edee532; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_budget_user_id_5edee532 ON public.account_budget USING btree (user_id);


--
-- TOC entry 4786 (class 1259 OID 118960)
-- Name: account_category_name_7e65caca_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_category_name_7e65caca_like ON public.account_category USING btree (name varchar_pattern_ops);


--
-- TOC entry 4803 (class 1259 OID 118990)
-- Name: account_notification_category_id_272e5093; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_notification_category_id_272e5093 ON public.account_notification USING btree (category_id);


--
-- TOC entry 4806 (class 1259 OID 118991)
-- Name: account_notification_user_id_520fbbdd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_notification_user_id_520fbbdd ON public.account_notification USING btree (user_id);


--
-- TOC entry 4809 (class 1259 OID 118997)
-- Name: account_savingsgoal_user_id_99ef1a0a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_savingsgoal_user_id_99ef1a0a ON public.account_savingsgoal USING btree (user_id);


--
-- TOC entry 4791 (class 1259 OID 118961)
-- Name: account_tag_name_0f6a5a73_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_tag_name_0f6a5a73_like ON public.account_tag USING btree (name varchar_pattern_ops);


--
-- TOC entry 4810 (class 1259 OID 119008)
-- Name: account_transaction_account_id_22b92a31; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_transaction_account_id_22b92a31 ON public.account_transaction USING btree (account_id);


--
-- TOC entry 4811 (class 1259 OID 119009)
-- Name: account_transaction_category_id_abcb9198; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_transaction_category_id_abcb9198 ON public.account_transaction USING btree (category_id);


--
-- TOC entry 4816 (class 1259 OID 119023)
-- Name: account_transaction_tags_tag_id_bbb462a9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_transaction_tags_tag_id_bbb462a9 ON public.account_transaction_tags USING btree (tag_id);


--
-- TOC entry 4817 (class 1259 OID 119022)
-- Name: account_transaction_tags_transaction_id_bc8f98b5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_transaction_tags_transaction_id_bc8f98b5 ON public.account_transaction_tags USING btree (transaction_id);


--
-- TOC entry 4758 (class 1259 OID 119052)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4763 (class 1259 OID 118875)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4766 (class 1259 OID 118876)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4774 (class 1259 OID 118891)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4777 (class 1259 OID 118890)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4780 (class 1259 OID 118905)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4783 (class 1259 OID 118904)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4771 (class 1259 OID 119047)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4830 (class 2606 OID 118962)
-- Name: account_account account_account_user_id_8d4f4816_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_account
    ADD CONSTRAINT account_account_user_id_8d4f4816_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4831 (class 2606 OID 118973)
-- Name: account_budget account_budget_category_id_f50af18e_fk_account_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_budget
    ADD CONSTRAINT account_budget_category_id_f50af18e_fk_account_category_id FOREIGN KEY (category_id) REFERENCES public.account_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4832 (class 2606 OID 118968)
-- Name: account_budget account_budget_user_id_5edee532_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_budget
    ADD CONSTRAINT account_budget_user_id_5edee532_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4833 (class 2606 OID 118980)
-- Name: account_notification account_notification_category_id_272e5093_fk_account_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_notification
    ADD CONSTRAINT account_notification_category_id_272e5093_fk_account_c FOREIGN KEY (category_id) REFERENCES public.account_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4834 (class 2606 OID 118985)
-- Name: account_notification account_notification_user_id_520fbbdd_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_notification
    ADD CONSTRAINT account_notification_user_id_520fbbdd_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4835 (class 2606 OID 118992)
-- Name: account_savingsgoal account_savingsgoal_user_id_99ef1a0a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_savingsgoal
    ADD CONSTRAINT account_savingsgoal_user_id_99ef1a0a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4838 (class 2606 OID 119012)
-- Name: account_transaction_tags account_transaction__transaction_id_bc8f98b5_fk_account_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_transaction_tags
    ADD CONSTRAINT account_transaction__transaction_id_bc8f98b5_fk_account_t FOREIGN KEY (transaction_id) REFERENCES public.account_transaction(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4836 (class 2606 OID 118998)
-- Name: account_transaction account_transaction_account_id_22b92a31_fk_account_account_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_transaction
    ADD CONSTRAINT account_transaction_account_id_22b92a31_fk_account_account_id FOREIGN KEY (account_id) REFERENCES public.account_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4837 (class 2606 OID 119003)
-- Name: account_transaction account_transaction_category_id_abcb9198_fk_account_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_transaction
    ADD CONSTRAINT account_transaction_category_id_abcb9198_fk_account_category_id FOREIGN KEY (category_id) REFERENCES public.account_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4839 (class 2606 OID 119017)
-- Name: account_transaction_tags account_transaction_tags_tag_id_bbb462a9_fk_account_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_transaction_tags
    ADD CONSTRAINT account_transaction_tags_tag_id_bbb462a9_fk_account_tag_id FOREIGN KEY (tag_id) REFERENCES public.account_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4824 (class 2606 OID 118870)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4825 (class 2606 OID 118865)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4826 (class 2606 OID 118885)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4827 (class 2606 OID 118880)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4828 (class 2606 OID 118899)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4829 (class 2606 OID 118894)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4840 (class 2606 OID 119061)
-- Name: authen_profilepicture authen_profilepicture_user_id_ee348a5e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authen_profilepicture
    ADD CONSTRAINT authen_profilepicture_user_id_ee348a5e_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2024-10-16 23:50:58

--
-- PostgreSQL database dump complete
--

