# Generated by Django 5.1.1 on 2024-10-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(to='account.tag'),
        ),
        migrations.DeleteModel(
            name='TransactionTag',
        ),
    ]
