# Generated by Django 5.1.1 on 2024-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_savingsgoal_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_type',
            field=models.CharField(choices=[('50b', '50% Budget Used'), ('75b', '75% Budget Used'), ('100b', '100% Budget Used'), ('100s', '100% Saving Goal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='account.tag'),
        ),
    ]
